### ISSUE TITLE
fix matomo >=4.0.0 compatibility

### ISSUE THREAD

**Issue by JanMalte** [digitalist-se/MatomoPlugin-Sentry#4] opened 2020-12-05 13:20 UTC
please update the compatibility to work with matomo >= 4.0.0

let me know if there is help needed and what we could do to push this forward.

**Comment by Findus23** [comment] 2020-12-05 13:29
Hi,

I didn't want to simply update the plugin as I stopped using sentry and didn't want to publish it without testing.

If you want to, I can update the composer dependencies and mark the plugin as 4.x compatible and you could test it before I publish it.

**Comment by Findus23** [comment] 2020-12-06 21:28
Hi,

You can find a hopefully Matomo 4 compatible version of the plugin in the 4.x-dev branch: https://github.com/Findus23/plugin-SentryLogger/tree/4.x-dev

**Comment by uhlhosting** [comment] 2021-01-26 23:41
@Findus23 the latest dev branch its simply broken for some reason after installing the latest 4.x-dev branch, I get this:

An error occurred
Package "sentry/sentry" is not installed

**Comment by Findus23** [comment] 2021-01-27 14:52
Hi,

The very concept of this plugin is (as mentioned in the description) very experimental and creating a separate vendor directory from the Matomo one is not how it is intended to be used and also the way Sentry is integrated is not really proper.

I created this plugin a while ago to quickly find exceptions in Matomo during testing and shared it in case someone else also found it useful, but then stopped using sentry and therefore also didn't use the plugin anymore. 

For your error I quickly tested it locally and I can enable the plugin without any errors, so I don't have any idea what could be the reason. But deleting the plugin/SentryLogger directory and the entries in the config/config.ini.php should get your Matomo instance working again.

**Comment by Findus23** [comment] 2021-01-29 17:34
@tsteur 
I now tried testing this on my live Matomo instance and indeed I get the same error.

It occurs on this line:
https://github.com/Findus23/plugin-SentryLogger/blob/6686f1003fd19a75deee21f14c0a7afd07d4e44f/SentryLogger.php#L32
which makes me think this is an autoloading issue.
Weirdly using composer for Matomo plugins should work (even the premium plugins do it). But maybe there is something weird when combining composer 2 with composer 1.
In my local dev instance everything works fine, so it might just be an issue with the released matomo package.

I can't think of any way to solve this so I'll probably just leave it as is until someone more familiar with composer comes across this.

**Comment by tsteur** [comment] 2021-01-31 21:53
Maybe @diosmosis or @sgiehl know more? I'm not so much into this unfortunately. If that's indeed the case we can't even easily change the composer version when packaging as it would maybe break other plugins.

**Comment by diosmosis** [comment] 2021-01-31 23:52
Not sure what the issue could be, but to test locally I'd download the vendor directories on your server locally and see if using those reproduces the issue locally. Then it'd be easier to debug at least.

**Comment by mikkeschiren** [comment] 2024-01-31 12:41
As Matomo 5 now is out, and we will have a branch for that, I am closing this.

**Closed by mikkeschiren** 2024-01-31 12:41 UTC
